// <auto-generated />
namespace IDP.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MigFirstInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigFirstInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202401221623011_Mig-FirstInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
